server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    key-store: classpath:www.gjyniubi.cn.jks
    key-store-password: q630qq1e943b
    key-store-type: JKS
spring:
  profiles:
    active: druid,dev
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 60s
    database: 0
  #连接池最大的连接数，若使用负值表示没有限制
    jedis:
      pool:
        max-active: 8
  #连接池最大阻塞等待时间，若使用负值表示没有限制
        max-wait: 60s
  #连接池中的最大空闲连接
        max-idle: 8
  #连接池中的最小空闲连接
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      add-mappings: false
# MyBatis
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: cn.gjyniubi.cinema.**.entry
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      update-strategy: ignored
      logic-delete-field: logicDel  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)